#!/bin/bash
# Copyright 2011-2012 Fatih Bostancı <faopera@gmail.com>
# v1.0.2


# şehir adı girilirse $1 önemsenmeyecek.
SEHIR=""

set -e
degerler=()
sehirler=( ADANA ADIYAMAN AFYONKARAHISAR AGRI AMASYA ANKARA ANTALYA ARTVIN AYDIN
           BALIKESIR BILECIK BINGOL BITLIS BOLU BURDUR BURSA CANAKKALE CANKIRI
           CORUM DENIZLI DIYARBAKIR EDIRNE ELAZIG ERZINCAN ERZURUM ESKISEHIR
           GAZIANTEP GIRESUN GUMUSHANE HAKKARI HATAY ISPARTA MERSIN ISTANBUL
           IZMIR KARS KASTAMONU KAYSERI KIRKLARELI KIRSEHIR KOCAELI KONYA
           KUTAHYA MALATYA MANISA KAHRAMANMARAS MARDIN MUGLA MUS NEVSEHIR
           NIGDE ORDU RIZE SAKARYA SAMSUN SIIRT SINOP SIVAS TEKIRDAG TOKAT
           TRABZON TUNCELI SANLIURFA USAK VAN YOZGAT ZONGULDAK AKSARAY BAYBURT
           KARAMAN KIRIKKALE BATMAN SIRNAK BARTIN ARDAHAN IGDIR YALOVA KARABUK
           KILIS OSMANIYE DUZCE )

if [[ -n ${SEHIR} ]]
then
    sehir="${SEHIR}"
elif [[ -n $1 ]]
then
    [[ $1 =~ ^0 ]] && s=${1/0/} || s=$1
    if [[ -n $(tr -d 0-9 <<<$1) ]]
    then
        printf "şehir trafik kodunu giriniz.\n" >&2
        exit 1
    elif [[ ${#1} -gt 2 ]]
    then
        printf "şehir trafik kodunu giriniz.\n" >&2
        exit 1
    elif [[ $s -gt 81 ]]
    then
        printf "şehir trafik kodunu giriniz.\n" >&2
        exit 1
    fi
    sehir=${sehirler[((s-1))]}
else
    printf "şehir trafik kodunu giriniz.\n" >&2
    exit 1
fi

wget --quiet --timeout=15 --tries=3 -O- "http://www.dmi.gov.tr/tahmin/il-ve-ilceler.aspx?m=${sehir}#sfB" | sed -n \
  '{/<div id="divSonDurum">/,/<\/div>/ s:<td><em class="renk.*">\(.*\)\&.*:\1 °C:p
  s:<td><em>\(.*\)</em></td>:\1:p
  s:<td><img.*title="\(.*\)" /> <br /><em>\(.*\)</em></td>:\1\n\2:p
  s:<td class="sond_zaman">\(.*\)<br .>\(.*\)</td>:\1\n\2:p}' > /tmp/hava-sonuclari-$$

while read -r satir
do
  degerler+=("${satir}")
done < /tmp/hava-sonuclari-$$

rm -f /tmp/hava-sonuclari-$$ &>/dev/null
[[ ${degerler[1]} =~ ^Güncel ]] && {
  degerler[0]="Sayfada bilgiler güncelleniyor..."
  degerler[1]=
}

printf '\n%-20s%b\n%-21s%b\n%-19s%b\n%-21s%b\n%-22s%b\n%-22s%b\n%-25s%b\n%-20s%b\n' \
  'Şehir' "= ${sehir}" \
  'Sıcaklık' "= ${degerler[2]}" \
  'Nem' "= ${degerler[3]}" \
  'Basınç' "= ${degerler[6]}" \
  'Rüzgar hızı' "= ${degerler[5]}" \
  'Rüzgar Yönü' "= ${degerler[4]}" \
  'Görüş uzaklığı' "= ${degerler[7]}" \
  'Son güncelleme' "= ${degerler[0]} ${degerler[1]}"

# vim: set ts=2 sw=2 noet:
